### ISSUE TITLE
Remove Due Dates

### ISSUE THREAD

**Issue by ramanxg** [icssc-projects/fellowship#45]
~~The due dates for the assignment are inconsistent. Some include the day (Monday, Tuesday, etc. ). Some also have incorrect (th), like `April 25nd at 11:59pm`.~~

~~We can make them all consistent to be: `Friday, June 3rd at 11:59pm`~~

Moving forward, the fellowship will be completely asynchronous, with students completing units at their own pace. Remove the due date from every unit in the fellowship.

**Comment by cami-p** [comment]
Claim! :)

**Comment by cami-p** [comment]
Hi @ramanxg, just wanted to clarify if I should be changing the due dates to the format "Weekday, Month Day(st, th, etc) at 11:59pm" or all to "Friday, June 3rd at 11:59pm"?

**Comment by ChaseC99** [comment]
Actually we decided we are going to remove all of the due dates. Moving forward, the fellowship will be completely asynchronous, with students completing units at their own pace. 

For this issue, would you mind deleting all due dates?
_(sorry for the last second change!)_

**Comment by cami-p** [comment]
Since the course is changing to self-guided pace, should I remove these sections on the syllabus as well?
![image](https://user-images.githubusercontent.com/103341440/173163412-bc3cbb35-57f2-45f4-b8d2-9087d18d987b.png)

**Comment by ChaseC99** [comment]
Oh yes please!
